version: '3.1'
services:
  mysql-db:
    image: mysql:8.3.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"